# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.3.4"

package:
  name: lomond
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/l/lomond/lomond-${{ version }}.tar.gz
  sha256: 250202a83ba45e3b265bf5dfef4db54d9c46b981230579dbe3b453dad320ba71

build:
  number: 0
  noarch: python
  script:
    env:
      PYTHONUTF8: "1"
    content: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - six >=1.10.0

tests:
  - python:
      imports:
        - lomond
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Websocket Client Library
  description: |
    Lomond is a websocket client library for Python that automatically
    handles persistent connections (with reconnect-on-failure), pings,
    proxy support, and emits a clean, easy-to-consume event stream.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://pypi.org/project/lomond/
  repository: https://github.com/wildfoundry/dataplicity-lomond

extra:
  recipe-maintainers:
    - rxm7706
